Debug why the demo fails to run and add a workaround for it
On JVM it's found caused by a compiler bug of calling `item`/`items`/`group`(now renamed with the "Internal" suffix) in `ListScope` with default arguments. The JVM error message:

> Task :demo:run
Gtk-Message: 18:27:31.940: Failed to load module "canberra-gtk-module"
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.huanshankeji.compose.material.ListScope.item$default(com.huanshankeji.compose.material.ListScope, java.lang.Object, java.lang.Object, kotlin.jvm.functions.Function3, int, java.lang.Object)'

The issue that `jsBrowserRun` fails to build seems to be caused by the same reason and is resolved too. Its original error message:

> Task :demo:compileDevelopmentExecutableKotlinJs FAILED
e: java.lang.AssertionError: Assertion failed

Now the demo works again on both platforms.