Bump `DependencyVersions`, run `kotlinUpgradeYarnLock`, and manually ensure that the demo app runs on JVM desktop, JS DOM, and Android
The app crashes on a "Small Phone" emulator because the screen is not wide enough.

The exception on Android:

```text
java.lang.IllegalArgumentException: maxWidth(-104) must be >= than minWidth(0)
```

The exception on JVM desktop when the window is narrowed:

```text
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: maxWidth(-21) must be >= than minWidth(0)
```