Update the demo `android` config DSL and resolve the bug that the Android app crashes by adding the Android target and refactoring `onClick`
From Logcat:

```text
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/foundation/OnClick_skikoKt;
```

```text
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/material3/ExposedDropdownMenu_skikoKt
```

It turns out that `Modifier.onClick` is not available for Android. See https://github.com/JetBrains/compose-multiplatform/issues/4468 for details.

A source commit: commit 47d0d80e0ae82a36f660e30d8fa16a4c072fb151