Extract common code that depends on code in the `androidx.compose` package into the `androidxCommon` source sets and support the Kotlin/Wasm target
Code is updated referencing a Compose Multiplatform project created with the new [Kotlin Multiplatform Wizard](https://kmp.jetbrains.com/). Memory has to be increased by setting `org.gradle.jvmargs=-Xmx2048M` in gradle.properties to compile to the Kotlin/Wasm target (when running `:wasmJsBrowserRun`). Otherwise, there is an `OutOfMemoryError`:

```text
java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
```